import type { Task, Submission } from './types';

export const MOCK_TASKS: Task[] = [
  {
    id: '0',
    poster: '0x7a3B...f29E',
    title: 'Build a Decentralized Voting DApp',
    spec: 'Create a decentralized voting application using Solidity smart contracts and React frontend. Must support creating proposals, voting with token-weighted ballots, and displaying results in real-time. Include comprehensive test coverage (>80%) and deploy to testnet.',
    repo_required: true,
    milestones: ['Smart contract with voting logic', 'React frontend with wallet connect', 'Token-weighted voting system', 'Test coverage >80%', 'Testnet deployment'],
    milestone_count: 5,
    status: 'completed',
    winner: '0x4eD1...a82C',
    reward: 2500,
    created_at: '2025-12-01',
    category: 'Smart Contract',
  },
  {
    id: '1',
    poster: '0x9cF2...b71A',
    title: 'NFT Marketplace API Integration',
    spec: 'Develop a REST API that aggregates NFT listings from OpenSea, Rarible, and LooksRare. Must include rate limiting, caching with Redis, pagination, and webhook support for price changes. Provide Swagger documentation.',
    repo_required: true,
    milestones: ['Multi-marketplace aggregation', 'Redis caching layer', 'Webhook notification system', 'Swagger API documentation'],
    milestone_count: 4,
    status: 'open',
    winner: '',
    reward: 1800,
    created_at: '2025-12-15',
    category: 'Backend',
  },
  {
    id: '2',
    poster: '0x3aB5...c94D',
    title: 'Cross-Chain Bridge Monitor Dashboard',
    spec: 'Build a real-time monitoring dashboard for cross-chain bridge transactions. Track transfers across Ethereum, Polygon, Arbitrum, and Optimism. Display volume metrics, pending transactions, and alert on anomalies.',
    repo_required: true,
    milestones: ['Multi-chain data ingestion', 'Real-time transaction tracking', 'Analytics dashboard UI', 'Anomaly detection alerts'],
    milestone_count: 4,
    status: 'judging',
    winner: '',
    reward: 3200,
    created_at: '2025-12-20',
    category: 'Frontend',
  },
  {
    id: '3',
    poster: '0x1dC8...e37F',
    title: 'ZK-Proof Identity Verification',
    spec: 'Implement a zero-knowledge proof system for age verification without revealing the actual birthdate. Must use circom circuits, generate proofs client-side, and verify on-chain with a Solidity verifier contract.',
    repo_required: true,
    milestones: ['Circom circuit design', 'Client-side proof generation', 'Solidity verifier contract', 'Integration tests'],
    milestone_count: 4,
    status: 'open',
    winner: '',
    reward: 5000,
    created_at: '2025-12-22',
    category: 'Cryptography',
  },
  {
    id: '4',
    poster: '0x8eA4...d56B',
    title: 'DeFi Yield Optimizer Bot',
    spec: 'Create an automated yield farming optimizer that monitors APY across Aave, Compound, and Curve, and automatically rebalances positions based on configurable strategies. Include backtesting framework.',
    repo_required: true,
    milestones: ['Multi-protocol APY monitoring', 'Auto-rebalancing engine', 'Strategy configuration UI', 'Backtesting framework'],
    milestone_count: 4,
    status: 'disputed',
    winner: '',
    reward: 4200,
    created_at: '2025-12-25',
    category: 'DeFi',
  },
  {
    id: '5',
    poster: '0x2fB7...a13G',
    title: 'On-chain Governance Analytics Tool',
    spec: 'Build a comprehensive analytics platform for DAO governance. Track voting patterns, delegate activity, proposal success rates, and voter engagement over time across major DAOs.',
    repo_required: false,
    milestones: ['Data aggregation pipeline', 'Governance metrics engine', 'Interactive visualization dashboard'],
    milestone_count: 3,
    status: 'open',
    winner: '',
    reward: 2800,
    created_at: '2025-12-28',
    category: 'Analytics',
  },
];

export const MOCK_SUBMISSIONS: Record<string, Submission> = {
  '0:0x4eD1...a82C': {
    submitter: '0x4eD1...a82C',
    github_url: 'https://github.com/example/voting-dapp',
    notes: 'Completed all milestones. Smart contracts deployed to Goerli testnet. Full test suite with 87% coverage.',
    verdict: {
      overall_pass: true,
      score: 92,
      reasoning: 'Excellent implementation covering all requirements. Smart contracts are well-structured with proper access control. Frontend provides a clean UX with wallet integration. Token-weighted voting is correctly implemented. Test coverage exceeds the 80% requirement at 87%. Successfully deployed to Goerli testnet.',
      milestones: [
        { name: 'Smart contract with voting logic', pass: true, reason: 'Well-structured contracts with proper access control and event emissions.' },
        { name: 'React frontend with wallet connect', pass: true, reason: 'Clean UI with WalletConnect and MetaMask support.' },
        { name: 'Token-weighted voting system', pass: true, reason: 'Correctly implements ERC20 balance-based voting weight.' },
        { name: 'Test coverage >80%', pass: true, reason: 'Hardhat coverage report shows 87% statement coverage.' },
        { name: 'Testnet deployment', pass: true, reason: 'Verified contract on Goerli at 0x1234...5678.' },
      ],
    },
    milestone_results: [
      { name: 'Smart contract with voting logic', pass: true, reason: 'Well-structured contracts with proper access control and event emissions.' },
      { name: 'React frontend with wallet connect', pass: true, reason: 'Clean UI with WalletConnect and MetaMask support.' },
      { name: 'Token-weighted voting system', pass: true, reason: 'Correctly implements ERC20 balance-based voting weight.' },
      { name: 'Test coverage >80%', pass: true, reason: 'Hardhat coverage report shows 87% statement coverage.' },
      { name: 'Testnet deployment', pass: true, reason: 'Verified contract on Goerli at 0x1234...5678.' },
    ],
  },
  '2:0x6bE3...c45A': {
    submitter: '0x6bE3...c45A',
    github_url: 'https://github.com/example/bridge-monitor',
    notes: 'Dashboard tracks ETH, Polygon, and Arbitrum. Optimism integration is in progress.',
    verdict: null,
    milestone_results: [],
  },
  '4:0x9dF2...b78C': {
    submitter: '0x9dF2...b78C',
    github_url: 'https://github.com/example/yield-optimizer',
    notes: 'Bot monitors Aave and Compound. Curve integration pending. Backtesting done for basic strategies.',
    verdict: {
      overall_pass: false,
      score: 58,
      reasoning: 'Partial implementation. Two of four protocols supported. Backtesting framework exists but is limited to simple strategies. Auto-rebalancing works but lacks proper slippage protection.',
      milestones: [
        { name: 'Multi-protocol APY monitoring', pass: false, reason: 'Only 2 of 3 required protocols (Aave, Compound) implemented. Curve is missing.' },
        { name: 'Auto-rebalancing engine', pass: true, reason: 'Functional rebalancing with configurable thresholds, but lacks slippage guards.' },
        { name: 'Strategy configuration UI', pass: true, reason: 'Clean UI for strategy parameters with real-time preview.' },
        { name: 'Backtesting framework', pass: false, reason: 'Basic framework exists but only supports simple strategies. No multi-protocol backtesting.' },
      ],
    },
    milestone_results: [
      { name: 'Multi-protocol APY monitoring', pass: false, reason: 'Only 2 of 3 required protocols (Aave, Compound) implemented. Curve is missing.' },
      { name: 'Auto-rebalancing engine', pass: true, reason: 'Functional rebalancing with configurable thresholds, but lacks slippage guards.' },
      { name: 'Strategy configuration UI', pass: true, reason: 'Clean UI for strategy parameters with real-time preview.' },
      { name: 'Backtesting framework', pass: false, reason: 'Basic framework exists but only supports simple strategies. No multi-protocol backtesting.' },
    ],
  },
};

export const STATS = {
  total_tasks: 6,
  judgments_made: 4,
  total_rewards: 19500,
  active_workers: 12,
};
